### ISSUE TITLE
[feature] add an API to allow sharing of grammar and input

### ISSUE THREAD

**Issue by hanjoes** [antlr/antlr4-lab#49]

**Comment by kaby76** [comment]
https://github.com/antlr/antlr4-lab/issues/8

I think the idea is to create a file with the tuple `grammar x start-symbol x input`. It can't be an html file that runs javascript to load http://lab.antlr.org then fill in the text boxes because it's a cross-domain page load, and javascript stops after loading lab.antlr.org (I tried). Likewise, a "put" doesn't work because it needs the UI up as well. The only solution that I can imagine that would work is to have a button in the UI to just read a file containing the tuple.

**Comment by parrt** [comment]
I think we have a solution in mind. Joe’s workin on it

**Comment by hanjoes** [comment]
ah, wasn't aware the discussions in #8, will give it more thought. This issue assumes we are going down the road of storing the tuple in a file.

**Comment by parrt** [comment]
I will mark this as a duplicate I guess.
